module.exports = {
  plugins: ['@ianvs/prettier-plugin-sort-imports'],
  trailingComma: 'all',
  singleQuote: true,
  printWidth: 80,
  tabWidth: 2,
  endOfLine: 'auto',
  importOrder: [
    '^react$',
    '<THIRD_PARTY_MODULES>',
    '',
    '^(@/)?App|AppearanceProvider|init|sentry|i18n$',
    '',
    '^(@/)?lottie/(.*)$',
    '',
    '^(@/)?test-utils$',
    '',
    '^(@/)?api/(.*)$',
    '',
    '^(@/)?types/(.*)$',
    '',
    '^(@/)?translations/(.*)$',
    '',
    '^(@/)?config$',
    '',
    '^(@/)?routePaths$',
    '',
    '^(@/)?customPalette$',
    '',
    '^(@/)?store$',
    '^(@/)?reducers/(.*)$',
    '',
    '^(@/)?providers/(.*)$',
    '',
    '^(@/)?pages/(.*)$',
    '',
    '^(@/)?containers/(.*)$',
    '',
    '^(@/)?components/(.*)$',
    '',
    '^(@/)?hooks/(.*)$',
    '',
    '^(@/)?query/(.*)$',
    '',
    '^(@/)?utils/(.*)$',
    '',
    // everything else except for images and styles
    '^(?!.*[.](css|scss|svg|png|jpg|gif)$)[./].*$',
    '',
    '^(@/)?images/(png|jpg|gif)$',
    '.(png|jpg|gif)$',
    '',
    '^(@/)?images/svg$',
    '.svg$',
    '',
    '^(@/)?styles/(.*)$',
    '.s?css$',
  ],
  importOrderParserPlugins: ['typescript', 'jsx'],
  importOrderTypeScriptVersion: '5.4.5',
};
